### ISSUE TITLE
Find a solution for servers that have been shut down

### ISSUE THREAD

**Issue by LaurenceBarnes** [ActualPlayer/RememberMe#3]
Hey, RememberMe is doing what it is supposed to do perfectly. However, there would be one QoL improvement I'd like to suggest: When a server that a player has been last online on is shut down, they are of course kicked, but they will not be sent back to the lobby server. Instead, they cannot connect at all anymore because the server they would join is offline.
If possible it would be beneficial if RememberMe would in that case use the Velocity try array. Perhaps it could be configurable whether someone wants that or not.

**Comment by LaurenceBarnes** [comment]
Using this Velocity build: 
https://ci.velocitypowered.com/view/Velocity/job/velocity-1.1.0/405/

Happens on previous builds as well from my experience. Thanks!

**Comment by ActualPlayer** [comment]
Fixed in #4
