### ISSUE TITLE
Forced Hosts shouldn't reconnect to last server

### ISSUE THREAD

**Issue by SenPr** [ActualPlayer/RememberMe#9]
When connecting through a forced host, plugin shouldn't reconnect the player to the last server but instead the server the forced host is assigned to.

**Comment by fgardt** [comment]
I fixed this and added more permissions in #6 but this repo seems rather inactive.
You could compile my updated version and use that instead if you feel ok with that.

**Comment by SenPr** [comment]
> I fixed this and added more permissions in #6 but this repo seems rather inactive. You could compile my updated version and use that instead if you feel ok with that.

I managed to do it myself a while ago, but yours look better. Thanks!
